import React from "react";
import "./Terms.scss";

export const Terms = () => {
  return (
    <div className="full-page-height terms-page section-padding">
      <div className="terms-content">
        <div>
          <h1 className="">Terms and conditions</h1>
        </div>
        <div>
          <span className="terms-text">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum suscipit commodi magni velit nihil. Commodi recusandae adipisci minus ratione iure modi odit ut hic dolorum, facere, id vitae accusamus explicabo autem quas blanditiis repellendus, architecto repudiandae doloribus quasi facilis unde cum. Eius, ipsa minima omnis accusamus nihil, ratione officia enim commodi temporibus dolorum in vitae fuga aliquam? Quae accusantium minus ducimus repudiandae, facilis deleniti sequi voluptates atque quod cupiditate praesentium soluta sint est maiores ipsa incidunt! Voluptate sint, suscipit dolores aliquid tempore debitis? Quidem
            voluptate aut quas? Quidem unde nisi aut dolorum excepturi provident temporibus aperiam, esse magni ullam! Quibusdam obcaecati magni ut, iure quis, molestias neque accusantium cupiditate vitae tempora ratione repellat eum, similique omnis laboriosam quia voluptas? Ut distinctio, reiciendis maxime perferendis quas delectus accusamus, corrupti sequi et aspernatur vel facilis! Eum dolor dolore quia quis amet dolores quisquam assumenda sunt dignissimos quidem odit quasi iusto numquam pariatur placeat, debitis enim iste quod rerum, atque nostrum? Cum distinctio, excepturi commodi libero deserunt nulla minus assumenda
            inventore corporis minima temporibus atque asperiores corrupti aspernatur itaque odit vitae architecto perspiciatis adipisci iste quasi autem sapiente. Reiciendis magni exercitationem debitis officiis laboriosam totam qui nobis illo et? Dolor magni deserunt voluptatum? Inventore ad sunt eligendi quas ea nobis, optio molestiae fugiat veritatis vitae porro quod at in temporibus nemo? Laborum ex, deserunt possimus et similique voluptas numquam aut, unde tempora aperiam, exercitationem inventore. Incidunt maiores reprehenderit aut delectus, labore dolores mollitia fugit vitae ex, placeat corrupti repellat perferendis
            perspiciatis quam modi explicabo assumenda id! Voluptas fuga dicta tempora ab velit asperiores esse. Odio, aperiam iusto sed temporibus aspernatur voluptate eveniet maxime vitae, fuga ipsam enim perspiciatis odit illo facilis eligendi doloribus culpa quo molestiae vel porro necessitatibus quae eum. Voluptatibus accusamus consequatur fuga optio eveniet aspernatur reprehenderit ut ducimus dicta? Nihil, placeat voluptatum magni temporibus sint accusamus vitae provident voluptates cupiditate quaerat reprehenderit, at, deserunt blanditiis quod saepe assumenda aut earum nulla incidunt sed voluptas repellendus porro eaque vero?
            Dolores facilis illo, ullam natus quidem in aperiam adipisci? Expedita, illo delectus deleniti eveniet eum repudiandae cumque corporis? Ducimus inventore maiores quidem exercitationem fugit quaerat non commodi consectetur rem voluptatum, repellat delectus dolorum architecto esse, vitae nam porro ipsa voluptas iusto blanditiis sunt! Dolorem inventore porro ducimus, magni ipsam aliquid dicta eos nemo maxime, modi autem eius eligendi facere! Magnam minus vero velit saepe distinctio qui vel molestias consequuntur cum eveniet cumque, ex, numquam facere optio, sunt voluptates beatae corporis dicta laboriosam autem. Ab aut quod
            fugiat, neque, illum suscipit sint voluptatibus tempora voluptates amet officiis! Corrupti molestias enim libero illo debitis adipisci dignissimos voluptas porro eligendi beatae quae velit laudantium sapiente accusantium, est quisquam laborum cumque ex, veritatis delectus nemo labore corporis! Repellat omnis, facere sequi, in tempore sint dolore aliquam atque a quibusdam nesciunt delectus enim nihil, placeat iste quis quae magni dignissimos soluta praesentium repudiandae eius sapiente autem. Adipisci harum modi sapiente at corrupti error et illo velit cupiditate! Recusandae distinctio, odio minus nihil quibusdam voluptas
            veniam maiores laboriosam culpa officia quasi consequatur deleniti. Odio non temporibus sed optio iste cum illum? Obcaecati sint facere dignissimos, odit quas quaerat voluptates soluta, aliquam facilis ipsa ex rem explicabo praesentium accusantium, pariatur alias fugit culpa dolore doloribus totam nulla eius! Doloremque magni a corporis reiciendis recusandae consequatur unde inventore optio tenetur temporibus illo ipsam corrupti in eius nemo, amet ea, doloribus, et beatae quis ad. Facere rerum sit nam nihil. Facilis, amet alias, eligendi error dolore, delectus tempore explicabo neque qui est corrupti doloremque itaque
            voluptatibus ab porro. Atque minus quae doloremque deleniti! Modi, voluptas. Reiciendis, quam saepe nam veniam dolor suscipit delectus, officiis accusantium facilis tempora, commodi enim soluta quidem facere! Amet explicabo dolorem mollitia suscipit eaque tempora blanditiis, doloremque aliquid facilis eum fugiat similique inventore accusantium perspiciatis quos odio, illo atque qui optio tempore, aperiam unde distinctio? Ut cum modi atque iste minus facilis voluptatum fuga ab sed necessitatibus doloremque soluta aliquam, perferendis sapiente at, porro quod sequi quis? Quos omnis id eos tenetur illum, quaerat officiis
            debitis repellendus nesciunt facere incidunt odit quibusdam, consequatur inventore quae odio modi vel voluptas aperiam adipisci excepturi? Ea porro similique rerum, dignissimos doloremque consequuntur assumenda? Ab architecto quos quia alias, mollitia eveniet.\
          </span>
        </div>
      </div>
    </div>
  );
};

export const Privacy = () => {
  return (
    <div className="full-page-height terms-page section-padding">
      <div className="terms-content">
        <div>
          <h1 className="">Privacy Policy</h1>
        </div>
        <div>
          <span className="terms-text">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum suscipit commodi magni velit nihil. Commodi recusandae adipisci minus ratione iure modi odit ut hic dolorum, facere, id vitae accusamus explicabo autem quas blanditiis repellendus, architecto repudiandae doloribus quasi facilis unde cum. Eius, ipsa minima omnis accusamus nihil, ratione officia enim commodi temporibus dolorum in vitae fuga aliquam? Quae accusantium minus ducimus repudiandae, facilis deleniti sequi voluptates atque quod cupiditate praesentium soluta sint est maiores ipsa incidunt! Voluptate sint, suscipit dolores aliquid tempore debitis? Quidem
            voluptate aut quas? Quidem unde nisi aut dolorum excepturi provident temporibus aperiam, esse magni ullam! Quibusdam obcaecati magni ut, iure quis, molestias neque accusantium cupiditate vitae tempora ratione repellat eum, similique omnis laboriosam quia voluptas? Ut distinctio, reiciendis maxime perferendis quas delectus accusamus, corrupti sequi et aspernatur vel facilis! Eum dolor dolore quia quis amet dolores quisquam assumenda sunt dignissimos quidem odit quasi iusto numquam pariatur placeat, debitis enim iste quod rerum, atque nostrum? Cum distinctio, excepturi commodi libero deserunt nulla minus assumenda
            inventore corporis minima temporibus atque asperiores corrupti aspernatur itaque odit vitae architecto perspiciatis adipisci iste quasi autem sapiente. Reiciendis magni exercitationem debitis officiis laboriosam totam qui nobis illo et? Dolor magni deserunt voluptatum? Inventore ad sunt eligendi quas ea nobis, optio molestiae fugiat veritatis vitae porro quod at in temporibus nemo? Laborum ex, deserunt possimus et similique voluptas numquam aut, unde tempora aperiam, exercitationem inventore. Incidunt maiores reprehenderit aut delectus, labore dolores mollitia fugit vitae ex, placeat corrupti repellat perferendis
            perspiciatis quam modi explicabo assumenda id! Voluptas fuga dicta tempora ab velit asperiores esse. Odio, aperiam iusto sed temporibus aspernatur voluptate eveniet maxime vitae, fuga ipsam enim perspiciatis odit illo facilis eligendi doloribus culpa quo molestiae vel porro necessitatibus quae eum. Voluptatibus accusamus consequatur fuga optio eveniet aspernatur reprehenderit ut ducimus dicta? Nihil, placeat voluptatum magni temporibus sint accusamus vitae provident voluptates cupiditate quaerat reprehenderit, at, deserunt blanditiis quod saepe assumenda aut earum nulla incidunt sed voluptas repellendus porro eaque vero?
            Dolores facilis illo, ullam natus quidem in aperiam adipisci? Expedita, illo delectus deleniti eveniet eum repudiandae cumque corporis? Ducimus inventore maiores quidem exercitationem fugit quaerat non commodi consectetur rem voluptatum, repellat delectus dolorum architecto esse, vitae nam porro ipsa voluptas iusto blanditiis sunt! Dolorem inventore porro ducimus, magni ipsam aliquid dicta eos nemo maxime, modi autem eius eligendi facere! Magnam minus vero velit saepe distinctio qui vel molestias consequuntur cum eveniet cumque, ex, numquam facere optio, sunt voluptates beatae corporis dicta laboriosam autem. Ab aut quod
            fugiat, neque, illum suscipit sint voluptatibus tempora voluptates amet officiis! Corrupti molestias enim libero illo debitis adipisci dignissimos voluptas porro eligendi beatae quae velit laudantium sapiente accusantium, est quisquam laborum cumque ex, veritatis delectus nemo labore corporis! Repellat omnis, facere sequi, in tempore sint dolore aliquam atque a quibusdam nesciunt delectus enim nihil, placeat iste quis quae magni dignissimos soluta praesentium repudiandae eius sapiente autem. Adipisci harum modi sapiente at corrupti error et illo velit cupiditate! Recusandae distinctio, odio minus nihil quibusdam voluptas
            veniam maiores laboriosam culpa officia quasi consequatur deleniti. Odio non temporibus sed optio iste cum illum? Obcaecati sint facere dignissimos, odit quas quaerat voluptates soluta, aliquam facilis ipsa ex rem explicabo praesentium accusantium, pariatur alias fugit culpa dolore doloribus totam nulla eius! Doloremque magni a corporis reiciendis recusandae consequatur unde inventore optio tenetur temporibus illo ipsam corrupti in eius nemo, amet ea, doloribus, et beatae quis ad. Facere rerum sit nam nihil. Facilis, amet alias, eligendi error dolore, delectus tempore explicabo neque qui est corrupti doloremque itaque
            voluptatibus ab porro. Atque minus quae doloremque deleniti! Modi, voluptas. Reiciendis, quam saepe nam veniam dolor suscipit delectus, officiis accusantium facilis tempora, commodi enim soluta quidem facere! Amet explicabo dolorem mollitia suscipit eaque tempora blanditiis, doloremque aliquid facilis eum fugiat similique inventore accusantium perspiciatis quos odio, illo atque qui optio tempore, aperiam unde distinctio? Ut cum modi atque iste minus facilis voluptatum fuga ab sed necessitatibus doloremque soluta aliquam, perferendis sapiente at, porro quod sequi quis? Quos omnis id eos tenetur illum, quaerat officiis
            debitis repellendus nesciunt facere incidunt odit quibusdam, consequatur inventore quae odio modi vel voluptas aperiam adipisci excepturi? Ea porro similique rerum, dignissimos doloremque consequuntur assumenda? Ab architecto quos quia alias, mollitia eveniet.\
          </span>
        </div>
      </div>
    </div>
  );
};
